services:
  authservice:
    extends:
      file: docker-compose.yml
      service: authservice
    ports: []
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - REVERSEPROXYCONFIG__LOGINPROXY=${INPUT_LOGIN_PROXY}
      - REVERSEPROXYCONFIG__APIPROXY=${INPUT_API_PROXY}
      - REVERSEPROXYCONFIG__PAYMENTPROXY=${INPUT_PAYMENT_PROXY}
      
  bionicplusapi:
    extends:
      file: docker-compose.yml
      service: bionicplusapi
    ports: []
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - REVERSEPROXYCONFIG__APIPROXY=${INPUT_API_PROXY}

  paymentservice:
    extends:
      file: docker-compose.yml
      service: paymentservice
    ports: []
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - REVERSEPROXYCONFIG__PAYMENTPROXY=${INPUT_PAYMENT_PROXY}
        
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${APPDATA}/ASP.NET/https:/https:ro