version: '3.4'

services:
  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    container_name: authservice
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
      - DBSETTINGS__NAME=Identity
      - DBSETTINGS__CONNECTIONSTRING=mongodb+srv://${INPUT_MONGO_DB_CREDS}@${INPUT_MONGO_DB_CLUSTER}/?retryWrites=true&w=majority
      - JWTCONFIG__ISSUERSIGNINGKEY=${INPUT_JWT_ISSUER_SIGNING_KEY}
      - JWTCONFIG__ISSUEDAUDIENCES=${INPUT_AUTH_AUDIENCE},${INPUT_API_AUDIENCE},${INPUT_PAYMENT_AUDIENCE}
      - JWTCONFIG__VALIDISSUER=${INPUT_VALID_ISSUER}
      - JWTCONFIG__VALIDAUTHAUDIENCES=${INPUT_AUTH_AUDIENCE}
      - JWTCONFIG__REFRESHTOKENVALIDITYINDAYS=30
      - JWTCONFIG__REFRESHTOKENKEY=${INPUT_REFRESH_TOKEN_KEY}
      - JWTCONFIG__REFRESHTOKENIV=${INPUT_REFRESH_TOKEN_IV}
      - ENDPOINTSCONFIG__CHECKACCOUNTURL=${INPUT_LOGIN_HOST}/api/v1/authenticate/check
      - ENDPOINTSCONFIG__LOGINURL=${INPUT_LOGIN_HOST}/api/v1/authenticate/login
      - ENDPOINTSCONFIG__EXTERNALLOGINURL=${INPUT_LOGIN_HOST}/api/v1/authenticate/login/external
      - ENDPOINTSCONFIG__REGISTERURL=${INPUT_LOGIN_HOST}/api/v1/authenticate/register
      - ENDPOINTSCONFIG__REFRESHTOKENSURL=${INPUT_LOGIN_HOST}/api/v1/authenticate/refresh
      - ENDPOINTSCONFIG__REVOKETOKENSURL=${INPUT_LOGIN_HOST}/api/v1/authenticate/revoke
      - ENDPOINTSCONFIG__CONFIRMEMAILURL=${INPUT_LOGIN_HOST}/api/v1/authenticate/confirm/email
      - ENDPOINTSCONFIG__RESENDCODEURL=${INPUT_LOGIN_HOST}/api/v1/authenticate/resend
      - ENDPOINTSCONFIG__FORGOTPASSWORDURL=${INPUT_LOGIN_HOST}/api/v1/authenticate/forgot/password
      - ENDPOINTSCONFIG__RECOVERPASSWORDURL=${INPUT_LOGIN_HOST}/api/v1/authenticate/recover/password
      - ENDPOINTSCONFIG__CHANGEPASSWORDURL=${INPUT_LOGIN_HOST}/api/v1/authenticate/change/password
      - ENDPOINTSCONFIG__CARDLISTURL=${INPUT_API_HOST}/api/Card/all
      - ENDPOINTSCONFIG__CARDURL=${INPUT_API_HOST}/api/Card
      - ENDPOINTSCONFIG__BASICCARDURL=${INPUT_API_HOST}/api/Card/basic
      - ENDPOINTSCONFIG__IMAGEUPLOADURL=${INPUT_API_HOST}/api/Images/upload
      - ENDPOINTSCONFIG__PROFILEURL=${INPUT_LOGIN_HOST}/api/profile
      - ENDPOINTSCONFIG__PROFILEUPDATEURL=${INPUT_LOGIN_HOST}/api/profile/profile
      - ENDPOINTSCONFIG__PROFILEUNITSURL=${INPUT_LOGIN_HOST}/api/profile/units
      - ENDPOINTSCONFIG__PROFILEMEASUREURL=${INPUT_LOGIN_HOST}/api/profile/measure
      - ENDPOINTSCONFIG__SURVEYURL=${INPUT_API_HOST}/api/Survey
      - ENDPOINTSCONFIG__SURVEYANSWERURL=${INPUT_API_HOST}/api/Survey/answer
      - ENDPOINTSCONFIG__SURVEYLISTURL=${INPUT_API_HOST}/api/Survey/my
      - ENDPOINTSCONFIG__SURVEYROLLBACKURL=${INPUT_API_HOST}/api/Survey/rollback
      - ENDPOINTSCONFIG__SURVEYRATEURL=${INPUT_API_HOST}/api/Survey/rate
      - ENDPOINTSCONFIG__PREGNANCYURL=${INPUT_API_HOST}/api/Pregnancy
      - ENDPOINTSCONFIG__CHILDRENURL=${INPUT_API_HOST}/api/Children
      - ENDPOINTSCONFIG__PAYMENTSERVICEURL=${INPUT_PAYMENT_HOST}
      - ENDPOINTSCONFIG__SUBSCRIPTIONURL=${INPUT_PAYMENT_HOST}/api/Subscription
      - ENDPOINTSCONFIG__CHECKOUTURL=${INPUT_PAYMENT_HOST}/api/Robokassa/checkout
      - ENDPOINTSCONFIG__PROMOCODEURL=${INPUT_PAYMENT_HOST}/api/Subscription/promocode
      - ENDPOINTSCONFIG__CALCULATEPRICEURL=${INPUT_PAYMENT_HOST}/api/Subscription/price/calculate
      - SETTINGSCONFIG__CAPTCHAKEY=${INPUT_CAPTCHA_KEY}
      - SETTINGSCONFIG__CAPTCHASECRET=${INPUT_CAPTCHA_SECRET}
      - SETTINGSCONFIG__GOOGLECLIENTIDWEB=${INPUT_GOOGLE_CLIENT_ID_WEB}
      - SETTINGSCONFIG__EXTERNALGOOGLEAUDIENCES=${INPUT_GOOGLE_CLIENT_ID_WEB}
      - PAYMENTCONFIG__INTERCEPTURL=auth.robokassa.ru/Merchant/State
      - EMAILCONFIGURATION__FROM=no-reply@babytips.me
      - EMAILCONFIGURATION__SMTPSERVER=email-smtp.us-east-1.amazonaws.com
      - EMAILCONFIGURATION__PORT=465
      - EMAILCONFIGURATION__USERNAME=${INPUT_SMTP_USER}
      - EMAILCONFIGURATION__PASSWORD=${INPUT_SMTP_PASSWORD}
  
  bionicplusapi:
    image: ${DOCKER_REGISTRY-}bionicplusapi
    build:
      context: .
      dockerfile: BionicPlusAPI/BionicPlusAPI/Dockerfile
    container_name: bionicplusapi
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8082
      - DBSETTINGS__NAME=MainDb
      - DBSETTINGS__CONNECTIONSTRING=mongodb+srv://${INPUT_MONGO_DB_CREDS}@${INPUT_MONGO_DB_CLUSTER}/?retryWrites=true&w=majority
      - JWTCONFIG__ISSUERSIGNINGKEY=${INPUT_JWT_ISSUER_SIGNING_KEY}
      - JWTCONFIG__VALIDISSUER=${INPUT_VALID_ISSUER}
      - JWTCONFIG__VALIDAPIAUDIENCES=${INPUT_API_AUDIENCE}
      - ENDPOINTSCONFIG__PAYMENTSERVICEURL=${INPUT_PAYMENT_HOST}
      - AWS__ACCESSKEY=${INPUT_AWS_ACCESS_KEY_ID}
      - AWS__SECRETKEY=${INPUT_AWS_SECRET_ACCESS_KEY}
      - AWS__REGION=eu-north-1
      - S3SETTINGS__BUCKETNAME=img-babytips.me

  paymentservice:
    image: ${DOCKER_REGISTRY-}paymentservice
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    container_name: paymentservice
    ports:
      - "8083:8083"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8083
      - JWTCONFIG__ISSUERSIGNINGKEY=${INPUT_JWT_ISSUER_SIGNING_KEY}
      - JWTCONFIG__VALIDISSUER=${INPUT_VALID_ISSUER}
      - JWTCONFIG__VALIDPAYMENTAUDIENCES=${INPUT_PAYMENT_AUDIENCE}
      - DBSETTINGS__NAME=MainDb
      - DBSETTINGS__IDENTITYNAME=Identity
      - DBSETTINGS__CONNECTIONSTRING=mongodb+srv://${INPUT_MONGO_DB_CREDS}@${INPUT_MONGO_DB_CLUSTER}/?retryWrites=true&w=majority
      - PLANSCONFIGURATION__FREEPLANID=${INPUT_FREE_PLAN_ID}
      - ALLOWEDIPS__ADRESSES=${INPUT_ALLOWED_IPS}
      - EMAILCONFIGURATION__FROM=no-reply@babytips.me
      - EMAILCONFIGURATION__SMTPSERVER=email-smtp.us-east-1.amazonaws.com
      - EMAILCONFIGURATION__PORT=465
      - EMAILCONFIGURATION__USERNAME=${INPUT_SMTP_USER}
      - EMAILCONFIGURATION__PASSWORD=${INPUT_SMTP_PASSWORD}
      - ENDPOINTSCONFIG__CANCELSUBSCRIPTIONBASEURL=${INPUT_PAYMENT_HOST}/api/Subscription/cancel
      - ENDPOINTSCONFIG__AUTHSERVICEURL=${INPUT_LOGIN_HOST}
      - MERCHANTINFO__PASSWORD1=${INPUT_MERCHANT_PASS1}
      - MERCHANTINFO__PASSWORD2=${INPUT_MERCHANT_PASS2}
      - SUBSCRIPTIONCONFIG__EXPIREDTIMEINMINUTES=${INPUT_SUB_EXPIRATION_TIME_MINUTES}
      - ENCRYPTIONCONFIG__USERIDSIGNINGKEY=${INPUT_JWT_ISSUER_SIGNING_KEY}
      - GOOGLEPLAYCONFIG__APPNAME=${GOOGLE_APP_NAME}
      - GOOGLEPLAYCONFIG__GOOGLECREDENTIALSCONFIGJSON=${GOOGLE_APP_CREDENTIALS_CONFIG_JSON}